### ISSUE TITLE
CUDA not available.

### ISSUE THREAD

**Issue by blahblkusoi** [thuml/Time-Series-Library#10]
EDIT: I resolved this issue by removing "export CUDA_VISIBLE_DEVICES=2" from the bash script. Didn't see that! Sorry for crowding the issue board.
----

I cannot get this to use the GPU. I can run other pytorch projects on my GPU, but this one does not detect CUDA.

When running the following code in my terminal:

```
import torch
print("CUDA AVAILABLE: ")
print(torch.cuda.is_available())
print("\nCUDA VERSION: ")
print(torch.version.cuda)
print("\nCUDA DEVICE: ")
print(torch.cuda.get_device_name(torch.cuda.current_device()))
```
I get the output:

```
CUDA AVAILABLE:
True

CUDA VERSION:
11.3

CUDA DEVICE:
NVIDIA GeForce RTX 2070 SUPER
```

If I put that exact same code within run.py directly after importing modules, I get this output:

```
CUDA AVAILABLE:
False

CUDA VERSION:
11.3

CUDA DEVICE:
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    print(torch.cuda.get_device_name(torch.cuda.current_device()))
  File "C:\Users\admin\anaconda3\envs\TN2\lib\site-packages\torch\cuda\__init__.py", line 481, in current_device
    _lazy_init()
  File "C:\Users\admin\anaconda3\envs\TN2\lib\site-packages\torch\cuda\__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

**Comment by htg17** [comment]
It is probably because you are using personal computer with one GPU available. In this case, you should set 
`export CUDA_VISIBLE_DEVICES=0`
in the first line of every scripts.

**Comment by WilliamLwj** [comment]
> It is probably because you are using personal computer with one GPU available. In this case, you should set `export CUDA_VISIBLE_DEVICES=0` in the first line of every scripts.

Had the same issue. This works like a charm. Thanks a lot!
