### ISSUE TITLE
CUDA 可用但运行模型时报错：No CUDA GPUs are available

### ISSUE THREAD

**Issue by Karesis** [thuml/Time-Series-Library#698]
## 问题描述
我在配置Time-Series-Library环境时遇到了奇怪的CUDA问题。在简单的测试中CUDA显示可用，但实际运行模型时却报错。

具体表现为：
- 单独运行`python -c "import torch; print(torch.cuda.is_available())"`返回`True`
- 但使用脚本运行模型时报错：`RuntimeError: No CUDA GPUs are available`

## 环境信息
- GPU: NVIDIA GeForce RTX 4070
- CUDA版本: 12.4
- 操作系统: Ubuntu Linux
- PyTorch: 按照requirements.txt安装的1.7.1（也尝试了兼容CUDA 12.1的更新版本）

## 复现步骤
1. 按照README指示安装环境（pip install -r requirements.txt）
2. 下载并放置数据集
3. 运行脚本：`bash ./scripts/long_term_forecast/ETT_script/TimesNet_ETTh1.sh`

## 错误信息
```
Use GPU: cuda:0
Traceback (most recent call last):
  ...
  File "/home/karesis/Project/Program/Time-Series-Library/.conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
```

## 尝试过的解决方案
1. 按照原始requirements.txt安装环境
2. 尝试安装与CUDA 12.1兼容的PyTorch版本
3. 重启系统
4. 设置CUDA_VISIBLE_DEVICES环境变量

奇怪的是，同一环境中运行`python -c "import torch; print(torch.cuda.is_available())"`返回`True`，说明PyTorch确实能识别到CUDA GPU。但运行模型时却无法使用GPU。

## 期望行为
模型应能正常使用GPU训练。

## 附加信息
目前只能通过设置`--use_gpu false`参数来使用CPU模式运行模型。

希望能得到关于这个问题的帮助或建议。谢谢！

**Comment by nkjff123** [comment]
您好，请问您解决了吗，我也遇到了这个问题

**Comment by jimxucoming** [comment]
你好，我也遇到过这个问题，是bash文件里有指定GPU的命令，注意修改下就可以了

**Comment by Karesis** [comment]
解决了，感谢

> 你好，我也遇到过这个问题，是bash文件里有指定GPU的命令，注意修改下就可以了
